#!/bin/sh

mypwd="`pwd`"

# Determine the location of this script...
# Note: this will not work if the script is sourced (. ./opatchauto)
SCRIPTNAME=$0
case ${SCRIPTNAME} in
/*)  SCRIPTPATH=`dirname "${SCRIPTNAME}"` ;;
  *)  SCRIPTPATH=`dirname "${mypwd}/${SCRIPTNAME}"` ;;
esac

# Delegate to the main script...
"${SCRIPTPATH}/auto/core/bin/opatchauto.sh" "$@"
RETURNCODE=$?
if [ "${RETURNCODE}" != "0" ]; then
  exit ${RETURNCODE}
fi
