-- Copyright (c) 2011,2016, Oracle and/or its affiliates. All rights reserved.
--
--
-- drop-rcu.sql - Drop tables for Weblogic core services for MySQL
-- 

-- drop the tables and views
DROP TABLE if EXISTS ACTIVE;
DROP TABLE if EXISTS WEBLOGIC_TIMERS;
DROP TABLE if EXISTS WLS_EVENTS;
DROP TABLE if EXISTS WLS_HVST;

-- drop batch tables
DROP TABLE if EXISTS CHECKPOINTDATA;
DROP TABLE if EXISTS EXECUTIONINSTANCEDATA;
DROP TABLE if EXISTS JOBINSTANCEDATA;
DROP TABLE if EXISTS JOBINSTANCEDATA_TRG;
DROP TABLE if EXISTS JOBSTATUS;
DROP TABLE if EXISTS STEPEXECUTIONINSTANCEDATA;
DROP TABLE if EXISTS STEPEXECUTIONINSTANCEDATA_TRG;
DROP TABLE if EXISTS STEPSTATUS;

-- drop security tables
DROP TABLE if EXISTS BEACSS_SCHEMA_VERSION;
DROP TABLE if EXISTS BEAPC;
DROP TABLE if EXISTS BEAPCM;
DROP TABLE if EXISTS BEAPRMP;
DROP TABLE if EXISTS BEARM;
DROP TABLE if EXISTS BEASAML2_CACHE;
DROP TABLE if EXISTS BEASAML2_ENDPOINT;
DROP TABLE if EXISTS BEASAML2_IDPPARTNER;
DROP TABLE if EXISTS BEASAML2_IDP_AUDIENCEURI;
DROP TABLE if EXISTS BEASAML2_IDP_PT_EP;
DROP TABLE if EXISTS BEASAML2_IDP_REDIRECTURI;
DROP TABLE if EXISTS BEASAML2_SPPARTNER;
DROP TABLE if EXISTS BEASAML2_SP_AUDIENCEURI;
DROP TABLE if EXISTS BEASAML2_SP_PT_EP;
DROP TABLE if EXISTS BEASAMLAP;
DROP TABLE if EXISTS BEASAMLAP_AURI;
DROP TABLE if EXISTS BEASAMLAP_ITP;
DROP TABLE if EXISTS BEASAMLAP_RURI;
DROP TABLE if EXISTS BEASAMLRP;
DROP TABLE if EXISTS BEASAMLRP_ACP;
DROP TABLE if EXISTS BEASAMLRP_AU;
DROP TABLE if EXISTS BEAUPC;
DROP TABLE if EXISTS BEAWCMCI;
DROP TABLE if EXISTS BEAWCRE;
DROP TABLE if EXISTS BEAWPCI;
DROP TABLE if EXISTS BEAWRCI;
DROP TABLE if EXISTS BEAXACMLAP;
DROP TABLE if EXISTS BEAXACMLAP_RS;
DROP TABLE if EXISTS BEAXACMLRAP;
DROP TABLE if EXISTS BEAXACMLRAP_R;
DROP TABLE if EXISTS BEAXACMLRAP_RS;

